### ISSUE TITLE
Sending messages to clients from other canisters and not from frontend

### ISSUE THREAD

**Issue by ktry1** [omnia-network/ic-websocket-cdk-mo#5]
Is it possible to send messages to all connected clients using intercanister calls?

I have a canister that has multiple public functions that update it's state. Separately, I have Gateway canister that is similar to [this example](https://github.com/iamenochchirima/ic-websockets-chat-mo/blob/main/src/chat_backend/main.mo). 

I am interested in this function:
```
// method called by the frontend SDK to send a message to the canister
  public shared ({ caller }) func ws_message(args : IcWebSocketCdk.CanisterWsMessageArguments, msg_type : ?AppMessage) : async IcWebSocketCdk.CanisterWsMessageResult {
    await ws.ws_message(caller, args, msg_type);
  };
```

Is there any way to change it for calling it from another canister? Or maybe there is a way to correctly generate args before calling this function? When we call from frontend, ic-websocket-js library generates the args for the message, but sadly I cannot understand how exactly it does this to do the same in a canister.

**Comment by Luca8991** [comment]
@ktry1 if I understood it correctly, you want to send a message from a canister that doesn't have the **ic-websocket-cdk** library to one or more frontend connected client(s), using a "gateway" canister. You can use the [IcWebSocket.send](https://mops.one/ic-websocket-cdk/docs#IcWebSocket.send) for this. Let me try to explain it better.

Let's say you have canister A, which runs your application logic, and canister B, which runs the **ic-websocket-cdk** library and acts as a "gateway" between canister A and frontend clients. In order to send a message from canister A to a connected client, you can follow these 2 steps:
1. expose a custom method on canister B similar to:
   ```motoko
   public shared func sendMessageToClient(client_principal : IcWebSocketCdk.ClientPrincipal, msg_bytes : Blob) : async IcWebSocketCdk.CanisterSendResult {
     await IcWebSocketCdk.send(ws_state, client_principal, msg_bytes);
   };
   ```
   We do something similar [in our test_canister](https://github.com/omnia-network/ic-websocket-cdk-mo/blob/344bd5edabfb24e5eff20d986aab168b4fe32d39/tests/test_canister/src/test_canister/main.mo#L66-L82).
2. call the `sendMessageToClient` method of canister B from canister A whenever you logic requires it, using an intercanister call.

In order for this to work, canister A needs to know the `client_principal` with which the client connects to canister B. This can be done with an intercanister call from canister B to canister A in the `on_open` callback, or the client could communicate it directly to canister A.

If you want to send a message to multiple clients at the same time, you may want to change the `sendMessageToClient` function to something like:
```motoko
public shared func sendMessageToClients(client_principals : [IcWebSocketCdk.ClientPrincipal], msg_bytes : Blob) : async IcWebSocketCdk.CanisterSendResult {
    var res : IcWebSocketCdk.CanisterSendResult = #Ok;

    label f for (client_principal in Array.vals(client_principals)) {
      switch (await IcWebSocketCdk.send(ws_state, client_principal, msg_bytes)) {
        case (#Ok(value)) {
          // Do nothing
        };
        case (#Err(error)) {
          res := #Err(error);
          break f;
        };
      };
    };

    return res;
};
```

The `ws_message` method that you mentioned is part of the IC WebSocket protocol, and shouldn't be used manually.

Does this answer your question?

By the way, we also have a Discord server where you can ask these questions: https://discord.gg/pxKdEAYvda.
